### ISSUE TITLE
Practical and economically viable solution

### ISSUE THREAD

**Issue by gauravkdesai** [w201rdada/portfolio-AngelaWuGitHub#1]
The problem that we are trying to solve here is of detecting fraudulent claims as early as possible with less or no human intervention.

This is nicely put in idea with clear financial reasons mentioned in introduction.  Also the solution talks about which parameters can be used for automatic fraud detection. 

What I would like to change is the proportion of intro vs solution vs conclusion. At the moment "Solution" part looks on smaller proportion than Intro+Conclusion. So I would suggest you cut down on Intro and Conclusion if possible.
Also in conclusion you should give hypothetical numbers on how much saving do you predict this method would provide.

**Comment by AngelaWuGitHub** [comment]
Thank you for your feedback! I have increased the "Solution" portion to make the idea look more balanced. 
I need to do more research to come up with hypothetical numbers that can reasonably represent the potential savings.
