### ISSUE TITLE
Remarks on insurance fraud

### ISSUE THREAD

**Issue by deepix** [w201rdada/portfolio-AngelaWuGitHub#2]
Insurance fraud is indeed a problem that merits innovative solutions.  Your idea is to use phone conversation in its entirety as input to a neural network.  This network is trained to identify fraudulent phone callers.  Based on what it says, further questioning may be undertaken.

One question I have is: how will you train the neural network?  You would need some labelled data.  I did not see an explicit mention of this.  Another question I have is on the training data set.  Do you have data only for US callers?  Can the neural network apply to non-US callers or cultures as well?

**Comment by AngelaWuGitHub** [comment]
Thank you for your feedback! Text mining techniques can be used to covert non-structured data to structured data. To answer your second question, text analyses and neural network models should work for US callers and non-US callers. Depending on the insurance jurisdictions the claimant resides, models may need to be tweaked to follow local insurance laws.
