### ISSUE TITLE
Comments/Feedback on Insurance Fraud Big Idea

### ISSUE THREAD

**Issue by danielle-altshuler** [w201rdada/portfolio-AngelaWuGitHub#3]
I really liked your big idea! I did not know that much about the industry, and this idea sounds VERY worthwhile. With insurance companies saving money on fraudulent claims, they would have a better ability to give people who really need it more money.

I believe it may be helpful to address at the beginning of the big idea how insurance companies figure out that a claim is fraud. Yes, I am assuming that your footnote will have all of this information, but a quick sentence or two may help set the stage for the rest of the big idea.

On top of my first point, how will the suspicious claim indicator be populated with "smart" data where we know a claim is or is not fraudulent? What makes a claim sound suspicious besides someone's gut? A quick overview of this process would be very helpful.

I believe that you started off really strong with the potential rebuttal with regards to claim timing. Do you have thoughts to improve customer satisfaction even with longer lead times?

**Comment by AngelaWuGitHub** [comment]
Thank you for the feedback! 
My second paragraph of the "Problem" section is meant to describe the two approaches insurers currently use to identify fraud. I will edit it to improve clarity. 
Through text mining, key words are identified and checked against credible sources to determine frauds. Sentiment analysis can also be used to detect unusual emotions.
To answer your third question, hopefully after the model being implemented for many months, the model will be able to accurately identify frauds with minimal false negatives.
