### ISSUE TITLE
Feedback for Idea #2 #2

### ISSUE THREAD

**Issue by brooksambrose** [w201rdada/portfolio-AngelaWuGitHub#5]
I think it is very well composed, thank you for learning from the feedback on the other draft.
You do a good job representing two clients, the video rental store first and yourself as a consumer second. The middle is very specific in terms of how data would be used and for what purpose. The ending is also a good summary. One thing to keep in mind is about how to handle "limitations" [here](https://github.com/w201rdada/portfolio-AngelaWuGitHub/blame/master/02.Rmd#L35). Really you don't want to be negative or reveal too serious a flaw; this is a communication strategy. If something is wrong pitch it as an additional feature to develop next, (maybe next time you pay the data scientist). That spins a downside into a next step. It's important to end on a positive note. Otherwise I think it's very effective, good job!

**Comment by AngelaWuGitHub** [comment]
Brooks, thanks for the suggestion! I revised the last paragraph and addressed the limitation with a future improvement to the model.
